"""init with constraint names

Revision ID: 72398bfee668
Revises: 
Create Date: 2025-04-23 14:18:59.299811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72398bfee668'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('application_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('columns_to_track', sa.Text(), nullable=True),
    sa.Column('database_retention_period', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flik_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['application_page.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flik_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['flik_role.id'], name='fk_flik_user_role_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('application_role_application_rule',
    sa.Column('application_role_id', sa.Integer(), nullable=True),
    sa.Column('application_rule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_role_id'], ['application_role.id'], name='fk_role_rule', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['application_rule_id'], ['application_rule.id'], name='fk_rule_role', ondelete='CASCADE')
    )
    op.create_table('bug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('application_role', sa.Integer(), nullable=True),
    sa.Column('application_page', sa.Integer(), nullable=True),
    sa.Column('assignee', sa.Integer(), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_page'], ['application_page.id'], ),
    sa.ForeignKeyConstraint(['application_role'], ['application_role.id'], ),
    sa.ForeignKeyConstraint(['assignee'], ['flik_user.id'], ),
    sa.ForeignKeyConstraint(['author'], ['flik_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flik_user_skill',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name='fk_user_skill_skill'),
    sa.ForeignKeyConstraint(['user_id'], ['flik_user.id'], name='fk_user_skill_user')
    )
    op.create_table('bug_skills',
    sa.Column('bug_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bug_id'], ['bug.id'], name='fk_bug_skill_bug', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name='fk_bug_skill_skill', ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bug_skills')
    op.drop_table('flik_user_skill')
    op.drop_table('bug')
    op.drop_table('application_role_application_rule')
    op.drop_table('flik_user')
    op.drop_table('application_rule')
    op.drop_table('skill')
    op.drop_table('flik_role')
    op.drop_table('configuration')
    op.drop_table('application_role')
    op.drop_table('application_page')
    # ### end Alembic commands ###
