"""initial clean migration

Revision ID: 7d9da6ec96bf
Revises: 
Create Date: 2025-04-22 13:24:13.468771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d9da6ec96bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_flik_user')
    with op.batch_alter_table('flik_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_flik_user_role_id', 'flik_role', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flik_user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_flik_user_role_id', type_='foreignkey')
        batch_op.drop_column('role_id')

    op.create_table('_alembic_tmp_flik_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=60), nullable=False),
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['flik_role.id'], name='fk_flik_user_role_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
