"""updated association table to flik_user_skill

Revision ID: a252ebc394fd
Revises: ae71ee7209c1
Create Date: 2025-04-03 12:37:26.028490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a252ebc394fd'
down_revision = 'ae71ee7209c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flik_user_skill',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['flik_user.id'], )
    )
    op.drop_table('user_skill')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_skill',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('skill_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['flik_user.id'], )
    )
    op.drop_table('flik_user_skill')
    # ### end Alembic commands ###
