"""added flikrole

Revision ID: a4f9455d360c
Revises: a252ebc394fd
Create Date: 2025-04-03 15:14:11.063782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f9455d360c'
down_revision = 'a252ebc394fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flik_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('flik_user_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['flik_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['flik_user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flik_user_roles')
    op.drop_table('flik_role')
    # ### end Alembic commands ###
