"""added ApplicationRule and association table with ApplicationRole

Revision ID: af8b14d3014d
Revises: 16e2c82046ec
Create Date: 2025-04-08 18:31:19.496103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af8b14d3014d'
down_revision = '16e2c82046ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['application_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_role_application_rule',
    sa.Column('application_role_id', sa.Integer(), nullable=True),
    sa.Column('application_rule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_role_id'], ['application_role.id'], ),
    sa.ForeignKeyConstraint(['application_rule_id'], ['application_rule.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_role_application_rule')
    op.drop_table('application_rule')
    # ### end Alembic commands ###
