"""added config table

Revision ID: c81800a0a799
Revises: e575fe1fe612
Create Date: 2025-04-17 18:38:33.271265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81800a0a799'
down_revision = 'e575fe1fe612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('columns_to_track', sa.Text(), nullable=True),
    sa.Column('database_retention_period', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuration')
    # ### end Alembic commands ###
