"""created bug table and association with skills

Revision ID: e575fe1fe612
Revises: d66bbab4e88d
Create Date: 2025-04-16 17:34:12.696048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e575fe1fe612'
down_revision = 'd66bbab4e88d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('application_role', sa.Integer(), nullable=True),
    sa.Column('application_page', sa.Integer(), nullable=True),
    sa.Column('assignee', sa.Integer(), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_page'], ['application_page.id'], ),
    sa.ForeignKeyConstraint(['application_role'], ['application_role.id'], ),
    sa.ForeignKeyConstraint(['assignee'], ['flik_user.id'], ),
    sa.ForeignKeyConstraint(['author'], ['flik_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bug_skills',
    sa.Column('bug_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bug_id'], ['bug.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bug_skills')
    op.drop_table('bug')
    # ### end Alembic commands ###
